[package]
name = "la-n-egg-rpq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.10.0"
nom = "7.1"
expect-test = "1.5.1"
libc = "0.2.0"
rand = "0.8"
